### ISSUE TITLE
Integrate @liskhq/lisk-p2p module in chain module

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#2873]
### Description
@liskhq/lisk-p2p library should be integrated into lisk-core, which leads to the next milestone `Introduce robust peer selection and banning mechanism`

### Child Issues
- [x] Create new network module #2874 
- [x] Update loader module in chain to use network module and fix the tests #2875
- [x] Update broadcaster to use network module and fix the tests #2878
- [x] Update consensus calculation to use network module and fix the tests #2881
- [x] Update transport module in chain to use network module and fix the tests #2877 
- [x] Update node module in chain to use network module and fix the tests #2880
- [x] Update API / peer and node status endpoints to use the network module (dependent on 1.6) #2879
- [x] Update DB to save existing peers #2882
- [x] Remove all the P2P related files (source and tests) from chain module #2883

**Comment by jondubois** [comment]
All these sub-issues should be merged into the `create_network_module` feature branch until they are all completed. Then we can merge into the `development` branch.

**Comment by diego-G** [comment]
For reference: https://github.com/LiskHQ/lisk/pull/3076#discussion_r269485996
