### ISSUE TITLE
Prepare file structure for Lisk application

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3146]
### Expected behavior
Move all the application-dependent files to the Lisk application-level folder (`lisk/src`) and implement the necessary logic to handle it in framework-level (`matcher` for transactions etc.):

- [x] Integrate constants.js into chain-specific configuration #3159
- [x] Narrow the list of supported by framework network parameters #3160
- [x] Move Lisk-specific transaction types to application-level #2780
- [x] Implement design pattern for protocol change #3251
- [x] Rename framework folder to core #3269 
- [x] Add lisk folder and move all of application related code #3270 

##### Optional 
~- [ ] Prepare a gateway for handling blockchain exceptions from application-level~

#### Dependencies
- [x] Move builds into application-level
- [x] Move Dockerfile into application-level
- [x] Cover application-level files by unit tests

### Actual behavior
Majority of necessary files are still in framework-level (`lisk/framework/`) and there is no implementation to handle it.

### Acceptance criteria
The following structure of the application-level folder (`lisk/src`) is:
```
/build
/config
 lisk.conf
 networks/
/transactions
 /exceptions (Optional)
 5.js
 6.js
 7.js
 /test
/test
app.js
package.json
```

### Notes
Please mind that summarily all of the Lisk transaction types will be disabled #3104, therefore the `matcher` implementation for transactions (more details in #2780) is obligatory and needs to be used by Lisk application.

### Which version(s) does this affect? (Environment, OS, etc...)
`1.6.0`
