### ISSUE TITLE
Improve the overall configuration

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3149]
### Expected behavior
Provide the unique and intuitive flow of configuration and validation of parameters in both Lisk Application and Lisk Framework. The configuration of applications using Lisk Framework should be easy. The configuration should be accessible for Lisk dependencies: build scripts, Docker and NewRelic.   

- [x] Create and use config.js script merging defaults and custom configuration #3171
- [x] Create new package.json in application-level #3172
- [x] Support ENV vars and console parameters in application-level #2976 
- [x] Use **selected** blockchain parameters from framework-level #3173
- [ ] Configure the framework's exceptions, constants, modules and components from application-level  #3174
- [x] Make each component/module responsible for validation its configuration #3196
   - [x] Update schema validation support for chain module on provided options #2959 
   - [x] Add schema validation support to storage component on provided options #2950 
   - [x] Add schema validation support to cache component on provided options #2947 
   - [x] Add schema validation support to system component on provided options #2940   
   - [x] Add schema validation support to logger component on provided options #2898

#### Optional 
- ~~Remove redundant "overrideModuleOptions" function~~ (Keep this)

#### Dependencies
- [ ] Update docker configuration to match with the new config
- [x] Update build process to work along with the new config
- [ ] Update and align lisk-commander with the new config

### Which version(s) does this affect? (Environment, OS, etc...)
`1.6.0`
