### ISSUE TITLE
Prepare README.md files describing the new repositories structure 

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-sdk#3153]
### Expected behavior
Write README files and provide the overview and explanation of the new Lisk repositories and their structure:
~~- [ ] Create README for custom transactions #3164~~ moved to 2.1.0
- [x] Create README for the application-level folder #3163
- [x] Update README for the framework-level folder #3162
- [x] Create README for framework #3161
- [x] Update README for the framework controller #3156
- [x] Update README for the framework modules #3157 
- [x] Update README for the framework components #3158 

### Which version(s) does this affect? (Environment, OS, etc...)
`1.6.0`
