### ISSUE TITLE
Introduce BFT module as described in the "Introduce BFT consensus protocol" LIP.

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#3560]
### Expected behavior
The "Introduce BFT consensus protocol" epic relies on the introduction of a BFT module. The salient points of the module are described in the LIP.

- [x] Create data structure to store block headers in sorted pattern #3691
- [x] Implement BFT LIP logic to add/remove headers as logic/bft.js #3692
- [x] Create submodule/bft to initiate the BFT logic at application startup #3693
- [x] Load minimum block headers on block deletion #3694
- [x] Persist BFT attribute heightFinalized as part of atomic block write #3695
- [x] Update the block processing to persist maxHeightPreviouslyForged #3696

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Comment by SargeKhan** [comment]
This is a complicated task which should be tackled in smaller issues. Therefore, the description of this issue should be updated to include a checklist of subtasks necessary to close this issue.
