### ISSUE TITLE
Implement Fast chain switching mechanism as per the specifications in Introduce BFT consensus protocol LIP 

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#3562]
### Expected behavior
The Introduce BFT consensus protocol LIP introduces Fast chain switching mechanism. This functionality should be implemented in the framework.

Linked tasks:
- [x] Implement mechanism for finding commonBlock #3769
- [x] Blocks need to be stored in temporary table on block deletion #3772
- [x] Blocks need to be restored from temporary table upon failure #3775
- [x] Implement functionality for removing blocks stored in temp table #3776
- [x] Blocks need to be restored from temporary table upon restart node #4348
- [x] Modify BSM logic for finding common block for FCS #4337
- [x] Query all blocks from common block for peer and validate for FCS #4338
- [x] Switch to different chain for FCS #4339

*Note for FCS: Forging is disabled during the whole process of moving to a different chain.*

### Actual behavior
The Fast chain switching mechanism is yet to be implemented in the framework.

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Comment by SargeKhan** [comment]
This is a complicated task which should be tackled in smaller issues. Therefore, the description of this issue should be updated to include a checklist of subtasks necessary to close this issue.
