### ISSUE TITLE
Implement block synchronization mechanism introduced in the Introduce BFT consensus protocol LIP.

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#3563]
### Expected behavior
Introduce BFT consensus protocol LIP introduces new specifications for a node to synchronize to the tip of the blockchain in the network. Therefore, the current syncing mechanism should be replaced with the new specification.

Child issues:
- [x] Implement Blocks Synchronizer class to combine Block Synchronization Mechanism logic #3773 
- [x] Implement peer selection algorithm step for Block Sync Mechanism #3767 
- [x] Implement obtain tip of chain step for Block Sync Mechanism #3768 
- [x] Implement reverting to last common block step for Block Sync Mechanism #3770 
- [x] Implement request and apply blocks of new chain step for Block Sync Mechanism #3771 
- [x] Update Application State interface to include heightPrevoted #3774 

### Actual behavior
The new specification for block synchronization is not implemented in framework.
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

**Comment by SargeKhan** [comment]
This is a complicated task which should be tackled in smaller issues. Therefore, the description of this issue should be updated to include a checklist of subtasks necessary to close this issue.
