### ISSUE TITLE
Blocks need to be restored from temporary table upon failure or application restart

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#3775]
### Expected behavior
Whenever the node crashes or upon failure during one of the sync processes we roll back to the original state by applying the blocks in the temp table and continue the operating of the node.

Functions to be implemented:
- `restoreBlocks()`

1. Read blocks from temp table
2. Apply blocks (blocks verify process - do not care about how it is implemented - just call this)
3. Remove temp blocks after the apply process is successful

### Design For Issue
Place the `restoreBlocks` in `blocks/blocks`.
The synchronizer class should injects `blocks module` as a dependency so we can access `restoreBlocks` inside.

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/improve-bft`

### Tasks list
- [ ] Add functionality for applying block from blocks temporary table.
- [ ] Restore blocks from the temporary table when the node restarts.
- [ ] Restore blocks from the temporary table when the synchronization fails.
- [ ] Write integration tests.

**Comment by sridharmeganathan** [comment]
@michielmulders will do the analysis before the next sprint grooming meeting.

**Comment by michielmulders** [comment]
[Conclusion STM about the approach of storing temporary data](https://github.com/LiskHQ/lisk-sdk/issues/3776#issuecomment-504935797).

**Comment by michielmulders** [comment]
First, happy path -> block in temp table and restore to chain (via test)
