### ISSUE TITLE
Fix and unskip the tests for applyTransaction function defined in transactionHandler

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk-sdk#3987]
### Expected behavior
There should be unit tests for the applyTransaction function in the transactionHandler.js file and they should not be skipped.
### Actual behavior
The tests defined for applyTransactions are skipped because they are not fixable with the current code structure.
### Steps to reproduce
Check the skipped tests.
### Which version(s) does this affect? (Environment, OS, etc...)
release/2.2.0

**Grooming Notes**

- It is really difficult to mock and stub now. We want to make the code more testable.
- Goal: fix tests but also refactor code in order to unskip skipped tests
- Needs discussion as in new block processor we want a new kind of interface on how we use state store. Figure out a way to make it easier to test.
- Also, we have to update the usages of this function.
- How big? For applyTransaction, multiple tests are skipped 15.

### Tasks list
- [ ] Refactor transactionHandler file to make code more testable.
- [ ] Update the usages of transactionHandler functions, and relevant tests.
- [ ] Unskip tests for applyTransactions function.
- [ ] Ensure transactionHandler file is covered with unit tests.
