### ISSUE TITLE
Remove old rounds related logic

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk-sdk#4168]
### Expected behavior
Remove the following functions:

- generateDelegateList
- updateDelegateListCache
- clearDelegateListCache
- getKeysSortByVote
- getDelegatesFromPreviousRound

Also, private methods that are only used inside these methods like `__private.getOutsiders` inside of `rounds.js`. 

### Tasks

- [ ] Remove old rounds related functions
- [ ] Check for any remaining private methods that are unused
- [ ] Remove old tests

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/improve-bft`

**Comment by lsilvs** [comment]
Will be done as part of https://github.com/LiskHQ/lisk-sdk/issues/3685
