### ISSUE TITLE
Remove tslint and use typescript-eslint

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4696]
### Description
`tslint` is deprecated in favor of eslint.
Therefore, it should migrate to https://github.com/typescript-eslint/typescript-eslint 

- [x] @liskhq/lisk-constants #5149 
- [x] @liskhq/lisk-api-client #5150 
- [x] @liskhq/lisk-cryptograpy #5153
- [x] @liskhq/lisk-passphrase #5155
- [x] @liskhq/lisk-transaction #5161 
- [x] @liskhq/lisk-transaction-pool #5164
- [x] @liskhq/lisk-validation #5165
- [x] @liskhq/lisk-chain	#5166
- [x] @liskhq/lisk-dpos #5169
- [x] @liskhq/lisk-bft #5178
- [x] @liskhq/lisk-p2p #5179
- [x] lisk-commander #5180
- [ ] lisk-elements #5181 
- [ ] @liskhq/lisk-client #5181 

### Actual behavior
It is using tslint
