### ISSUE TITLE
Introduce new passphrase encryption algorithm 

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#6952]
### LIP

LIPs are still in staging or docs

### Motivation

Improve passphrase security by selecting better encryption algorithm for storing the passphrase.

### Tasks

Key Derivation

- [x] https://github.com/LiskHQ/lisk-sdk/issues/7192
- [x] https://github.com/LiskHQ/lisk-sdk/issues/7193
- [x] https://github.com/LiskHQ/lisk-sdk/issues/7194
- [x] https://github.com/LiskHQ/lisk-sdk/issues/7195
- [x]  https://github.com/LiskHQ/lisk-sdk/issues/7196

Key Encryption
- [x] https://github.com/LiskHQ/lisk-sdk/issues/7203
- [x] https://github.com/LiskHQ/lisk-sdk/issues/7204
- [x] https://github.com/LiskHQ/lisk-sdk/issues/7205
